server:
  port: 8081

logging:
  level:
    liquibase: INFO
upload:
  path: /home/dru/dev/sweater/uploads
spring:
  freemarker:
    expose-request-attributes: true
  datasource:
    url: jdbc:postgresql://localhost:5432/reference-storage
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        search:
          default:
            directory__provider: filesystem
            indexBase: /data/index
  mvc:
    static-path-pattern: /static/**

  mail:
    transport:
      protocol: smtp
    from:
      email: link.storage@yandex.ru
    username: link.storage@yandex.ru
    password: link.storage1
    host: smtp.yandex.ru
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
