<@c.page>
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <title>Доступ запрещен</title>
    </head>
    <body>
    <h3 align="center">
        <img src="/static/pics/error_img.png" alt="Ошибка 503">Доступ запрещен!</h3>
    </body>
    <footer>
        <a href="http://www.freepik.com" style="font-size: 10px">Designed by Freepik</a>
    </footer>
    </html>
</@c.page>